# This playbook install the mongoose (http://code.google.com/p/mongoose/) web
# server.
#
# Copyright (c) 2013-2020 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install mongoose package
  dnf:
    pkg: "{{ item }}"
    state: present 
  with_items:
    - mongoose

- name: create a directory for mongoose
  file:
    path: /var/www/mongoose
    mode: 0755
    state: directory

- name: copy mongoose systemd service file
  template:
    src: files/mongoose-service.j2 
    dest: /lib/systemd/system/mongoose.service
    owner: root
    group: root
    mode: 0644

- name: reload systemd
  command: /usr/bin/systemctl --system daemon-reload

- name: start mongoose
  service:
    name: mongoose
    state: running
    enabled: yes 

- name: configure firewall, allow traffic to port 8889
  firewalld:
    port: 8889/tcp
    permanent: true
    state: enabled

