# This playbook install the PhpSysInfo (http://rk4an.github.com/phpsysinfo/) 
# php application.
#
# Copyright (c) 2013-2019 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install additional php packages
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - php-xml 
    - php-mbstring

- name: download the phpsysinfo source tarball
  get_url:
    url: https://github.com/rk4an/phpsysinfo/archive/v{{ phpsysinfo_version}} .tar.gz
    dest: /var/www/lighttpd/phpsysinfo-{{ phpsysinfo_version }}.tar.gz
    mode: 0440

- name: unpack the source tarball
  command: /usr/bin/tar -xzf /var/www/lighttpd/phpsysinfo-{{ phpsysinfo_version }}.tar.gz -C /var/www/lighttpd/

- name: rename the source directory
  command: /usr/bin/mv /var/www/lighttpd/phpsysinfo-{{ phpsysinfo_version}}  /var/www/lighttpd/phpsysinfo

- name: delete the archive
  file:
    path: /var/www/lighttpd/phpsysinfo-{{ phpsysinfo_version }}.tar.gz
    state: absent

- name: copy the default config file
  command: /usr/bin/cp /var/www/lighttpd/phpsysinfo/phpsysinfo.ini.new /var/www/lighttpd/phpsysinfo/phpsysinfo.ini

- name: add a new entry to the index.html page
  lineinfile:
    dest: /var/www/lighttpd/index.html
    regexp: '^<!--IN-->'
    insertafter: '        <!--IN-->'
    line: '        <a href="/phpsysinfo" class="btn btn-primary">phpSysInfo</a>'
