# This playbook install all needed components for the setup.
#
# Copyright (c) 2013-2020 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: update all packages
  command: /usr/bin/yum -y update

- name: install additional packages
  dnf:
    pkg: "{{ item }}"
    state: present
  with_items:
    - unzip
    - tar
    - git
    - wget

- name: distribute system_identification file
  template:
    src: files/system_identification.j2
    dest: /etc/system_identification
    owner: root
    group: root
    mode: =0644
