# This playbook creates a PXE server.
#
# Copyright (c) 2013-2020 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install needed packages
  dnf:
    pkg: "{{ item }}"
    state: present
  with_items:
    - tftp-server
    - syslinux

- name: copy prelinux.0 from syslinux installation
  command: /usr/bin/cp /usr/share/syslinux/pxelinux.0 /var/lib/tftpboot/pxelinux.0

- name: copy vesamenu.c32 from syslinux installation
  command: /usr/bin/cp /usr/share/syslinux/vesamenu.c32 /var/lib/tftpboot/vesamenu.c32

- name: copy memdisk from syslinux installation
  command: /usr/bin/cp /usr/share/syslinux/memdisk /var/lib/tftpboot/memdisk

- name: create the pxelinux.cfg directory
  file:
    path: /var/lib/tftpboot/pxelinux.cfg
    mode: 0755
    state: directory

- name: create the tmp directory for storing the configuration fragments
  file:
    path: /var/lib/tftpboot/pxelinux.cfg/tmp
    mode: 0755
    state: directory

- name: copy the background image for the menu
  copy:
    src: files/pxe/background.png
    dest: /var/lib/tftpboot/background.png

- name: put a configuration fragement for default part in place
  template:
    src: files/pxe/000-default.j2
    dest: /var/lib/tftpboot/pxelinux.cfg/tmp/000-default
    mode: 0644

# PXE elements ###############################################################
# 001 - 009: Default local operations
- include: tasks/pxe/001-local.yml
- include: tasks/pxe/008-separator.yml

## No sub menu
# 010 - 069: Operating system
#- include: tasks/pxe/010-submenu-start.yml
- include: tasks/pxe/011-fedora.yml
#- include: tasks/pxe/012-fsl-tb.yml
#- include: tasks/pxe/013-live.yml
- include: tasks/pxe/019-rescue.yml
- include: tasks/pxe/020-freedos.yml
- include: tasks/pxe/030-sl.yml
- include: tasks/pxe/031-co.yml
- include: tasks/pxe/040-debian.yml
- include: tasks/pxe/050-xpud.yml
#- include: tasks/pxe/060-alpine.yml
- include: tasks/pxe/070-kali.yml
#- include: tasks/pxe/069-submenu-end.yml

## Sub menu
# 070 - 089: Tools
- include: tasks/pxe/070-submenu-start.yml
- include: tasks/pxe/071-memtest.yml
- include: tasks/pxe/072-dban.yml
- include: tasks/pxe/073-hdt.yml
- include: tasks/pxe/074-partedmagic.yml
- include: tasks/pxe/089-submenu-end.yml

# 090 - 099: Local operations
- include: tasks/pxe/090-separator.yml
- include: tasks/pxe/098-reboot.yml
- include: tasks/pxe/099-shutdown.yml
# Finishing tasks #############################################################

- name: assemble the default file
  assemble:
    src: /var/lib/tftpboot/pxelinux.cfg/tmp
    dest: /var/lib/tftpboot/pxelinux.cfg/default

- name: delete the tmp directory
  file:
    path: /var/lib/tftpboot/pxelinux.cfg/tmp
    state: absent

- name: set the permission
  file:
    path: /var/lib/tftpboot/pxelinux.cfg/default
    mode: 0644
    state: file

- name: enable tftp in xinetd
  command: /usr/bin/sed -i 's|\sdisable\s\{3,\}= yes|\tdisable \t\t= no|g' /etc/xinetd.d/tftp

- name: configure firewall, allow traffic to port 69 for tftp
  firewalld:
    port: 69/tcp
    permanent: true
    state: enabled

- name: reload firewall configuration
  command: /usr/bin/firewall-cmd --reload

- name: start and enable xinetd service
  service:
    name: xinetd
    state: running
    enabled: yes

