# This playbook install the redis (http://www.redis.io/) data structure server.
#
# Copyright (c) 2013-2020 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install redis and related packages
  dnf:
    pkg: "{{ item }}"
    state: present 
  with_items:
    - redis

- name: start redis
  service:
    name: redis-server
    state: running
    enabled: yes
